# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# See https://wiki.hyprland.org/Configuring/Monitors/

# SchnuBby Einstellung
monitor = DP-4, 1920x1080@144, auto, auto
monitor = DP-5, 1920x1200, 1920x0, auto

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    #force_no_accel = 1
    accel_profile = flat
}
